title: Copper OS
email: racooder@racoonia.net
description: A operating system for computercraft and what goes with it.
baseurl: "/copper-os/"
url: "https://racooder.github.io"
github_username: Racooder

markdown: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
