title: Copper OS
email: racooder@racoonia.net
description: A operating system for computercraft and what goes with it.
baseurl: "/copper-os/docs/"
url: "https://racooder.github.io"
github_username: Racooder

markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
